version: '3.7'
services:
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./:/var/www/youtube-api.s4g.miage.dev:cached']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./:/var/www/youtube-api.s4g.miage.dev:cached']