version: '3.7'
services:
  php:
    image: stream4good/youtube-api-php
    ports: ['9000:9000']
    environment:
      - "APP_ENV=dev"
      - "APP_SECRET=44337def4a6f25da0f7a252cb6001e1f"
      - "DATABASE_URL=mysql://svocale:n7Hc3K8mQ@hn105529-001.dbaas.ovh.net:35552/youtube?serverVersion=5.7"
      - "CORS_ALLOW_ORIGIN='*'"
      - "PREFIX='https://youtube-api-s4g.miage.dev'"
      - "REDIS_LINK='redis://localhost'"
      - "SHORT_EXPIRATION=3600"
      - "LONG_EXPIRATION=3600*24"
      - "RABBITMQ_URL=amqp://admin:Veipheibochah7gi2iwa7eeho@broker-s4g.miage.dev:5672"

  web:
    image: stream4good/youtube-api-web
    ports: ['80:80']    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.rule=host(`youtube-api-s4g.miage.dev`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=80"
