api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  title: "S4G Youtube-API"
  description: "S4G Youtube-API Paris 1 MIAGE"
  show_webby: false
  collection:
    pagination:
      enabled: false

  # Enable the entrypoint.
  enable_entrypoint: false

  enable_re_doc: true
