old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            read_write_timeout: 4
            heartbeat: 2
    producers:
        messaging:
            class: App\Rabbit\MessagingProducer
            connection:       default
            exchange_options: { name: 'celery', type: direct }
    consumers:
        messaging:
            connection:       default
            exchange_options: { name: 'youtube-response', type: direct }
            queue_options:    { name: 'youtube-response'}
            callback:         message_service
            enable_logger:    true

