<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpjTApZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpjTApZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMpjTApZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMpjTApZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMpjTApZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MpjTApZ',
    'container.build_id' => '060c966d',
    'container.build_time' => 1618361447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpjTApZ');
